export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const CONTACTS_LOADING = "CONTACTS_LOADING";
export const CONTACTS_SUCCESS = "CONTACTS_SUCCESS";
export const CONTACTS_ERROR = "CONTACTS_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_CONTACT_LOADING = "ADD_CONTACT_LOADING";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_ERROR = "ADD_CONTACT_ERROR";
export const CLEAR_ADD_CONTACT = "CLEAR_ADD_CONTACT";
